package com.fullteaching.selenium;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CreateAndDeleteCourseTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "C:\\Users\\Flavio\\OneDrive\\Área de Trabalho\\trabalhos QT\\Trabalho - Testes Unitarios - Flavia\\full-teaching-master\\chromedriver.exe");

    var options = new ChromeOptions();
    options.addArguments("ignore-certificate-errors");


    driver = new ChromeDriver(options);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void createAndDeleteCourse() {
    driver.get("http://localhost:5000/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    {
      WebElement element = driver.findElement(By.cssSelector("li:nth-child(2) > .navbar-button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("li:nth-child(2) > .navbar-button")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("teacher@gmail.com");
    driver.findElement(By.id("password")).sendKeys("pass");
    driver.findElement(By.id("password")).sendKeys(Keys.ENTER);

    WebDriverWait wait = new WebDriverWait(driver, 3000);
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("add-course-icon")));

    driver.findElement(By.id("add-course-icon")).click();
    driver.findElement(By.id("input-post-course-name")).click();
    driver.findElement(By.id("input-post-course-name")).sendKeys("Novo Curso");
    driver.findElement(By.id("submit-post-course-btn")).click();

    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".collection-item:nth-child(3) .material-icons")));
    driver.findElement(By.cssSelector(".collection-item:nth-child(3) .material-icons")).click();
    driver.findElement(By.id("label-delete-checkbox")).click();
    driver.findElement(By.id("delete-course-btn")).click();
    driver.findElement(By.id("arrow-drop-down")).click();

    driver.findElement(By.id("logout-button")).click();
  }
}
